# Generated by Django 4.2.10 on 2024-04-25 18:32

from django.db import migrations, models
import django.db.models.deletion
import whistleblower_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=whistleblower_app.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('user', models.CharField(default='No User Data Available', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('Physical Bullying', 'Physical Bullying'), ('Verbal Abuse', 'Verbal Abuse'), ('Cyberbullying', 'Cyberbullying'), ('Racist Bullying', 'Racist Bullying'), ('Inappropriate Sexual Comments', 'Inappropriate Sexual Comments'), ('Social Bullying', 'Social Bullying'), ('Emotional Intimidation', 'Emotional Intimidation'), ('Other', 'Other')], max_length=30)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='whistleblower_app.submission')),
            ],
        ),
    ]
