# Generated by Django 4.2.10 on 2024-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whistleblower_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(default="No Description Available."),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user",
            field=models.CharField(default="No User Data Available", max_length=255),
        ),
    ]
