# Generated by Django 4.2.10 on 2024-04-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_app', '0002_uploadedfile_description_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
