# Generated by Django 4.2.10 on 2024-04-15 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("whistleblower_app", "0004_submission_uploadedfile_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
