# Generated by Django 4.2.10 on 2024-04-16 00:57

from django.db import migrations, models
import whistleblower_app.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "whistleblower_app",
            "0005_alter_submission_id_alter_uploadedfile_description",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.UUIDField(
                default=whistleblower_app.models.generate_unique_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
