# Generated by Django 4.2.10 on 2024-04-16 00:57

from django.db import migrations, models
import whistleblower_app.models
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def extend_postgresql_uuid(sender, connection, **kwargs):
    if connection.vendor == 'postgresql':
        cursor = connection.cursor()
        cursor.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    if 'postgresql' in db_alias:
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission ADD COLUMN new_id UUID DEFAULT uuid_generate_v4();')
        schema_editor.execute('UPDATE whistleblower_app_submission SET new_id = uuid_generate_v4();')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission DROP COLUMN id CASCADE;')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission RENAME COLUMN new_id TO id;')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission ALTER COLUMN id SET NOT NULL;')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission ADD PRIMARY KEY (id);')

class Migration(migrations.Migration):
    dependencies = [
        ('whistleblower_app', '0005_alter_submission_id_alter_uploadedfile_description'),
    ]

    operations = [
        migrations.RunPython(apply_migration, reverse_code=migrations.RunPython.noop),
    ]