# Generated by Django 4.2.10 on 2024-04-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whistleblower_app", "0006_alter_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="tag",
            field=models.CharField(
                choices=[
                    ("physical", "Physical Bullying"),
                    ("verbal", "Verbal Abuse"),
                    ("cyber", "Cyberbullying"),
                    ("racism", "Racist Bullying"),
                    ("sexual", "Inappropriate Sexual Comments"),
                    ("social", "Social Bullying"),
                    ("emotional", "Emotional Intimidation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
