# Generated by Django 4.2.10 on 2024-04-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_app', '0007_uploadedfile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='tag',
            field=models.CharField(choices=[('Physical Bullying', 'Physical Bullying'), ('Verbal Abuse', 'Verbal Abuse'), ('Cyberbullying', 'Cyberbullying'), ('Racist Bullying', 'Racist Bullying'), ('Inappropriate Sexual Comments', 'Inappropriate Sexual Comments'), ('Social Bullying', 'Social Bullying'), ('Emotional Intimidation', 'Emotional Intimidation'), ('Other', 'Other')], max_length=30),
        ),
    ]
