# Generated by Django 4.2.10 on 2024-04-25 11:33

from django.db import migrations, models
import uuid

def add_uuid_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    if 'sqlite' in db_alias:
        Submission = apps.get_model('whistleblower_app', 'Submission')
        schema_editor.execute('ALTER TABLE whistleblower_app_submission ADD COLUMN new_id TEXT DEFAULT NULL;')
        submissions = Submission.objects.using(db_alias).all()
        for submission in submissions:
            submission.new_id = str(uuid.uuid4())
            submission.save()
        schema_editor.execute('ALTER TABLE whistleblower_app_submission RENAME TO temp_submission;')
        schema_editor.execute('CREATE TABLE whistleblower_app_submission (id TEXT NOT NULL PRIMARY KEY, ...);')
        schema_editor.execute('INSERT INTO whistleblower_app_submission (id, ...) SELECT new_id, ... FROM temp_submission;')
        schema_editor.execute('DROP TABLE temp_submission;')

class Migration(migrations.Migration):
    dependencies = [
        ('whistleblower_app', '0008_alter_uploadedfile_tag'),  # Adjust according to your actual dependency.
    ]

    operations = [
        migrations.RunPython(code=add_uuid_field, reverse_code=migrations.RunPython.noop),
    ]
