# Generated by Django 4.2.10 on 2024-04-25 18:09

from django.db import migrations, models
import whistleblower_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_app', '0009_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.TextField(default=whistleblower_app.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
